version: "3"

services:
  url-app:
    restart: always
    build: ./
    expose: 
       - 9091
    ports:
      - 9091:9091
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  rabbitmq:
    image: rabbitmq:3.7-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
   mongodata: