server:  
  port: ${PORT:9091}
  servlet:
    context-path: /
spring:
  profiles: default
  rabbitmq:
    host: rabbitmq
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: urlDb